version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - 2609:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/confs:/etc/nginx/conf.d
        networks:
            - default
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=role_heroes_database
            - DB_PORT=5432
        volumes:
            - ./:/var/www
            - ./docker/php/confs/php.ini:/usr/local/etc/php/php.ini
        networks:
            - default
    database:
        image: postgres:latest
        container_name: role_heroes_database
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks:
            - default
networks:
    default:
