version: '3.7'

services:
    web:
        build:
            context: .
            target: web
        image: role/web
        ports:
            - ${DEV_PORT}:80
        environment:
            SERVER_NAME: "role.com"
        volumes:
            - ./public:/var/www/public
        depends_on:
            - app
    app:
        build:
            context: .
            target: app
            args:
                APP_ENV: "local"
        environment:
            - DB_CONNECTION=pgsql
            - DB_HOST=role_heroes_database
            - DB_PORT=5432
        image: role/app
        volumes:
            - ./:/var/www

    database:
        image: postgres:latest
        container_name: role_heroes_database
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        networks:
            - default

networks:
    default:
